# Generated by Django 4.1.1 on 2022-09-13 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('isbn', models.PositiveIntegerField()),
                ('category', models.CharField(max_length=100)),
                ('available', models.CharField(max_length=100)),
                ('is_add_date', models.DateField(auto_now=True)),
                ('is_add_time', models.TimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_created', models.DateTimeField(auto_now=True)),
                ('is_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
